language: ruby
rvm:
- 2.7.0
env:
  global:
  - TRAVIS_NODE_VERSION="v8.9.4"
  matrix:
    secure: b/V9oimWlG9xb+w1+vKrthLVzTfNCpiKFXU9EnpE2S7tIpqPuBesBZKBMSagNG5tfOZvjfPqH9yqMryxos92yZhHF2u1/yHIGYJvrA61E+hIplNUrAlbVTxuE4ckGZX+hz0PDDJ8sVSUSMqn6V9BIxZRyCFKU0Nf5t96WZ/G1l0CR4EReTASfmoZsepuFIf/42FmCOvrUStAy4JSXIn/DVpqR3y5CWYEyljtci3iunW5qngvhpdMUDulYBnWvYSdy19Qpspo6asH7AwZQ3hVO9OUF5bIk3GmUndPIUMZwwOAlR4Gy05jfNZamE7oX7NjCDB+MIrO5dY+3Q6I6II5QS44fCx1lcWwzaODshXZUvo7rshIoz85hv2CYnmCINY3P0fvhGwyYjwuEXR43cA3dhT8eqGwksiryp4VRbHvHtzpafOYf4wBDM1FGtLtRPGsRNzKunvnpHvH8paI0rx2yFTEuT+pbqDHPGh/n0v5DZoqP0QaUKpXduMaqLCSMF7Sfznd2QD+YiYvCS3LDk0hwlcWKfGmqhAOljHAfMwzCzOPpCXSqq0MGbjtBxNC/BBPoBELYJPDiaCc4/xri46a7DcXjGhCSoiUDSIFM0C3e0gms+kji7wsueOtws/ZPV9TJKxu0InfZc1ZHkwOF6ZZU2yMLkdZh3XQmFhP/OaWSaw=
before_install:
- chmod +x ./.build_scripts/deploy.sh
before_script:
- ". $HOME/.nvm/nvm.sh"
- nvm install $TRAVIS_NODE_VERSION
- nvm use $TRAVIS_NODE_VERSION
- npm install -g gulp
- npm install
script: gulp prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: false
  on:
    branch: publish
  local_dir: _site
